from fpdf import FPDF
from datetime import datetime

# Theme Colors
COLOR_BG = (10, 10, 15)       # Cyber Dark
COLOR_CARD = (20, 20, 25)     # Card BG
COLOR_TEXT = (255, 255, 255)  # White
COLOR_ACCENT = (0, 240, 255)  # Cyan
COLOR_SEC = (139, 92, 246)    # Purple
COLOR_BORDER = (40, 40, 50)   # Border

class PDFReport(FPDF):
    def header(self):
        # Draw Background
        self.set_fill_color(*COLOR_BG)
        self.rect(0, 0, 210, 297, 'F')
        
        # Header Line
        self.set_fill_color(*COLOR_CARD)
        self.rect(0, 0, 210, 30, 'F')
        
        # Title
        self.set_font('Arial', 'B', 16)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(10)
        self.cell(0, 15, 'SCANCRYPT', 0, 0, 'L')
        
        self.set_font('Arial', '', 10)
        self.set_text_color(*COLOR_TEXT)
        self.cell(0, 15, 'Confidential Security Audit', 0, 0, 'R')
        self.ln(25)

    def sanitize(self, text):
        if text is None:
            return ""
        # Handle special chars
        return str(text).encode('latin-1', 'replace').decode('latin-1')

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f'Generated by Scancrypt Neural Engine - Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 14)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(0, 10, self.sanitize(title), 0, 1, 'L')
        
        self.set_fill_color(*COLOR_SEC)
        self.rect(self.get_x(), self.get_y(), 200, 0.5, 'F') # Underline
        self.ln(5)

    def card_entry(self, label, value, new_line=True):
        self.set_font('Arial', 'B', 10)
        self.set_text_color(*COLOR_ACCENT)
        self.cell(25, 6, label, 0, 0)
        
        self.set_font('Arial', '', 10)
        self.set_text_color(*COLOR_TEXT)
        
        # Handle multi-line for value
        if len(str(value)) > 80:
            self.ln(6)
            self.multi_cell(0, 5, self.sanitize(value))
        else:
            self.cell(0, 6, self.sanitize(value), 0, 1 if new_line else 0)

    def generate(self, scan_data, filename="report.pdf"):
        self.add_page()
        
        # --- COVER SECTION ---
        self.ln(10)
        self.set_font('Arial', 'B', 24)
        self.set_text_color(255, 255, 255)
        self.cell(0, 15, self.sanitize(scan_data.get('target', 'Unknown Website')), 0, 1, 'C')
        
        self.set_font('Arial', '', 12)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Scan Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, 'C')
        self.ln(10)

        # Risk Score Badge (Simulated)
        score = scan_data.get('risk_score', 0)
        self.set_fill_color(*COLOR_CARD)
        self.rect(10, self.get_y(), 190, 40, 'F')
        self.set_y(self.get_y() + 5)
        
        self.set_font('Arial', 'B', 14)
        self.set_text_color(255, 255, 255)
        self.cell(0, 10, f"Overall Risk Score: {score}/10", 0, 1, 'C')
        
        risk_color = (100, 255, 100) if score < 4 else (255, 165, 0) if score < 7 else (255, 50, 0)
        self.set_fill_color(*risk_color)
        self.rect(55, self.get_y(), score * 10, 5, 'F') # Progress bar
        self.ln(20)

        # --- EXECUTIVE SUMMARY ---
        self.chapter_title("Executive Summary")
        findings = scan_data.get('findings', [])
        
        counts = {"Critical": 0, "High": 0, "Medium": 0, "Low": 0, "Info": 0}
        for f in findings:
            sev = f.get('severity', 'Info')
            if sev in counts: counts[sev] += 1
            
        # Summary Grid
        start_y = self.get_y()
        col_width = 38
        self.set_fill_color(*COLOR_CARD)
        
        self.set_xy(10, start_y)
        for sev in ["Critical", "High", "Medium", "Low", "Info"]:
            self.rect(self.get_x(), self.get_y(), col_width - 2, 20, 'F')
            
            # Label
            self.set_font('Arial', 'B', 10)
            if sev == "Critical": self.set_text_color(168, 85, 247) # Purple
            elif sev == "High": self.set_text_color(239, 68, 68)   # Red
            elif sev == "Medium": self.set_text_color(245, 158, 11) # Amber
            elif sev == "Low": self.set_text_color(59, 130, 246)    # Blue
            else: self.set_text_color(148, 163, 184)
            
            self.cell(col_width - 2, 8, sev, 0, 2, 'C')
            
            # Count
            self.set_font('Arial', 'B', 16)
            self.set_text_color(255, 255, 255)
            self.cell(col_width - 2, 8, str(counts.get(sev, 0)), 0, 0, 'C')
            
            self.set_xy(self.get_x() + col_width, start_y)
            
        self.ln(25)

        # --- DETAILED FINDINGS ---
        self.chapter_title("Detailed Findings")
        
        for i, finding in enumerate(findings, 1):
            if self.get_y() > 250: # Page break check
                self.add_page()
            
            # Card Background
            current_y = self.get_y()
            # Estimate height (rough)
            # We'll draw AFTER content or just background rect?
            # FPDF is imperative. Draw rect first.
            self.set_fill_color(*COLOR_CARD)
            # We don't know height yet. 
            # Strategy: Draw Header with Severity color
            
            severity = finding.get('severity', 'Info')
            sev_color = (150, 150, 150)
            if severity == 'Critical': sev_color = (168, 85, 247)
            elif severity == 'High': sev_color = (239, 68, 68)
            elif severity == 'Medium': sev_color = (245, 158, 11)
            elif severity == 'Low': sev_color = (59, 130, 246)
            
            # Side Strip
            self.set_fill_color(*sev_color)
            self.rect(10, current_y, 2, 30, 'F') # Indicator strip
            
            self.set_xy(15, current_y)
            self.set_font('Arial', 'B', 12)
            self.set_text_color(*sev_color)
            name = finding.get('name', 'Vulnerability')
            self.cell(0, 8, self.sanitize(f"#{i}  {name}"), 0, 1)
            
            # Details
            self.set_x(15)
            self.card_entry("URL:", finding.get('url'))
            
            if finding.get('parameter'):
                self.set_x(15)
                self.card_entry("Param:", finding.get('parameter'))
                
            if finding.get('payload'):
                self.set_x(15)
                self.card_entry("Payload:", finding.get('payload'))
                
            self.ln(2)
            self.set_x(15)
            self.set_font('Arial', 'I', 10)
            self.set_text_color(200, 200, 200)
            desc = finding.get('description', 'No description.')
            self.multi_cell(0, 5, self.sanitize(desc))
            
            self.ln(2)
            self.set_x(15)
            self.set_font('Arial', 'B', 10)
            self.set_text_color(*COLOR_ACCENT)
            self.cell(0, 6, "Remediation:", 0, 1)
            self.set_x(15)
            self.set_font('Arial', '', 10)
            self.set_text_color(*COLOR_TEXT)
            self.multi_cell(0, 5, self.sanitize(finding.get('remediation', '')))
            
            self.ln(8)
            # Separator
            self.set_draw_color(*COLOR_BORDER)
            self.line(10, self.get_y(), 200, self.get_y())
            self.ln(5)

        self.output(filename)
        return filename
